### ISSUE TITLE
Request: orb numbers at laveka

### ISSUE THREAD

**Issue by Ethaw** [NielsH/RaidCore#7]
It seems raidcore and lui_bossmods count orbs differently (except at start, then at some point they are unsynced, which forces a raid to use one addon or the other, can't mix it because of this).

It would be great if you could use the same counting as lui bossmods so people can choose which addon they use without interfering with kick assignments.

**Comment by ivangg** [comment]
For some unknown reason, Lui resets the orb timer after every midphase (see here: https://github.com/laserloui/LUI-BossMods/blob/master/Encounters/RMT/Laveka.lua#L539).

We don't think this should be default for counting orb kicks. We prefer to have a continuous flow - so we won't be changing this. It might be worth asking Lui to fix his part (removing the line I linked would sync Lui Bossmods to Raidcore).

**Comment by Zod-** [comment]
Guess I have to do this anyway. Gonna add it this evening probably
